First Look
rudyghill/cviche pull request #1
Opened 2024-03-20 06:25 UTC by philipmassouh

I made some changes/improvements/suggestions here. I am going to comment more notes

2024-03-20 06:28 UTC, philipmassouh reviewed
lgtm bro

2024-03-20 06:28 UTC, philipmassouh commented on cviche.py
> +   skl = auto()
enums are nice, can use `is` check instead of `==` when comparing to them.

2024-03-20 06:28 UTC, philipmassouh commented on cviche.py
>      master = utilities.csv_to_table(csv)
I recommend `pandas` with `read_csv`

2024-03-20 06:28 UTC, philipmassouh commented on cviche.py
>      return utilities.select_values_with_tag(master, "skill", "tags", tag)
symbolic constants

2024-03-20 06:28 UTC, philipmassouh commented on cviche.py
>      master = utilities.csv_to_table(filename)
filename can be a `Path` object: `from pathlib import Path`

2024-03-20 06:28 UTC, philipmassouh commented on utilities.py
> +def replace_placeholders(document: str, replacements: dict[str, str]) -> str:
typehints

2024-03-20 21:38 UTC, rudyghill commented on utilities.py
> +def replace_placeholders(document: str, replacements: dict[str, str]) -> str:
I like this and need this

2024-03-20 21:39 UTC, rudyghill commented on cviche.py
> +   skl = auto()
I'm going to drop this because I have plans to make cviche more general like we talked about

2024-03-20 21:52 UTC, rudyghill requested changes
I like what I am seeing but can you discard the enum? And can you verify the program won't crash by using the Path types?

And for now, I don't think I will use pandas

2024-03-20 21:52 UTC, rudyghill commented on cviche.py
>      master = utilities.csv_to_table(filename)
I'll bring in these changes, but I need to make sure I'm using path right such that my program doesn't crash

2024-03-21 19:00 UTC, rudyghill approved these changes
I removed the enums myself

2024-03-21 19:00 UTC, merged